### ISSUE TITLE
Unknown error in Explain tab

### ISSUE THREAD

**Issue by LamaTe** [LamaTe/mlr3shiny#11]
When trying to compute dependence graphs, the computation sometimes fails due to package conflicts.

Error message:
`Error: Package ‘rlang’ version 0.4.12 cannot be unloaded: Error in unloadNamespace(package) : namespace ‘rlang’ is imported by ‘ellipsis’, ‘tibble’, ‘ggplot2’, ‘cachem’, ‘purrr’, ‘testthat’, ‘vctrs’, ‘pillar’, ‘lifecycle’, ‘shiny’, ‘shinytest’, ‘htmltools’, ‘sass’, ‘bslib’ so cannot be unloaded`

**Comment by DominicTheHOST** [comment]
should be resolved with new explain tab implementation
