### ISSUE TITLE
Error in Explain tab for twoclass task

### ISSUE THREAD

**Issue by g-rho** [LamaTe/mlr3shiny#12]
1)
Task 
 - Select german credit
 - set potitive class to good
 Learner
- Learner 1: logistic regression
Predict
- Select learner 1
- Train learner
Explain
- Select learner 1
- Select features: age, amount, credit history duration

Error message:

It seems that the selected learner does not fully support the current data. Please review the dataset and check if the learner can work with all features present.

Error: ‘log’ not meaningful for factors

2)  ...continued from 1)
Explain
- Change loss function to CE

Error message:

It seems that the selected learner does not fully support the current data. Please review the dataset and check if the learner can work with all features present.

Error: Assertion on 'length(features) == length(feature.type)' failed: Must be TRUE.

**Comment by g-rho** [comment]
REM: This is related to the use of ordered factors 8and how they are treated within iml) --> generally, it the behaviour for ordered predictors should be tested (e.g. using the german credit data -- variables instalment_rate, number_of_credits & present_residence) as there is e.g. the pipe operator for SVMs.

**Comment by Jiaro** [comment]
this issue has been documented in the iml-Repository ([Issue](https://github.com/christophM/iml/issues/185)).
iml can not handle features with multiple classes atm.

**Comment by DominicTheHOST** [comment]
Migrated to DALEX. This should have fixed this issue
