### ISSUE TITLE
Chat with us about the package?

### ISSUE THREAD

**Issue by pat-s** [LamaTe/mlr3shiny#2]
Hi Laurens,

great to see your initiative here!
Would you want to chat with us about your future aims and the current state of the package?
You might as well want to move the package into the mlr-org?

Right now the name suggests its an official package of the mlr3 ecosystem but so far we never talked about this in detail. Happy to do so - please talk to us in our Mattermost group 🙂

**Comment by LamaTe** [comment]
Hi Patrick,

good to hear from you. I had some chat with Michel from time to time and planned to discuss this with you, too. Let's transfer this discussion to Mattermost :)
