### ISSUE TITLE
Disable change of predict type for twoclass classif

### ISSUE THREAD

**Issue by g-rho** [LamaTe/mlr3shiny#5]
Disable change of predict type for twoclass classif (Learner tab). If possible, add an according pop up hint for the mouse pointer.

**Comment by LamaTe** [comment]
Affected functionalities:
* Learner overview
* Change predict type tab

**Comment by LamaTe** [comment]
Fixed in commit 6eaab0d838a9a3cacfe44b1a39f7ed84bb85caa2
