### ISSUE TITLE
xgb parameters can't be changed (!)

### ISSUE THREAD

**Issue by g-rho** [LamaTe/mlr3shiny#72]
repex:
- [task: iris -> no change]
- learner: xgboost -> change parameter eta to e.g. 0.2 -> click change parameters

Warning: Error in if: argument is of length zero
  2: shiny::runApp
  1: mlr3shiny::launchMlr3Shiny

**Comment by DominicTheHOST** [comment]
Fixed with Commit 72f9e385e9926af5b5164df3dd780f29c5b1b3ad
