### ISSUE TITLE
check feasibility of adding mlr3viz::autoplot for task 

### ISSUE THREAD

**Issue by g-rho** [LamaTe/mlr3shiny#73]
- maintainability aspects
- additonal window below the task definition   
- is there space for the plots?
- ...type = "pair" (classif & regr) vs. "duo" (only classif)
- add (conditional) menu to select/deselect features for the plot (such as in the task processing window but the task should be cloned (?) as the features should not be removed from the task but only for the plot)

**Comment by Albatros131** [comment]
Erfolgreich umgesetzt
